const CURRENT_SEASON_ID = '2026_q3_apollo';

const SEASON_DB = {
    "2026_q2_orion": {
        id: "2026_q2_orion",
        name: "Orion Anomaly Season (2026 Q2)",
        cardEnabled: true,
        badgePath: "static/orion/",
        endTime: "2026-06-30T23:59:59",
        tiers: [
            { name: 'Bronze', value: 5000, color: 'rgba(205,127,50,0.5)' },
            { name: 'Silver', value: 8000, color: 'rgba(192,192,192,0.5)' },
            { name: 'Gold', value: 15000, color: 'rgba(255,215,0,0.5)' },
            { name: 'Platinum', value: 25000, color: 'rgba(229,228,226,0.5)' }
        ],
        activities: [
            { id: 'bounties', nameKey: 'act_bounties', descKey: 'desc_bounties', max: 6720, unit: 'tokens', isBounty: true },
            { id: 'ifs_apr', nameKey: 'act_ifs_apr', descKey: 'desc_ifs_apr', max: 2500, unit: 'tokens' },
            { id: 'ifs_may', nameKey: 'act_ifs_may', descKey: 'desc_ifs_may', max: 2500, unit: 'tokens' },
            { id: 'ifs_jun', nameKey: 'act_ifs_jun', descKey: 'desc_ifs_jun', max: 2500, unit: 'tokens' },
            { id: 'op_sakura', nameKey: 'act_op_sakura', utcStart: '2026-04-07T18:00:00Z', utcEnd: '2026-04-30T18:00:00Z', max: 3000, unit: 'tokens' },
            { id: 'op_global', nameKey: 'act_op_global', utcStart: '2026-04-24T18:00:00Z', utcEnd: '2026-05-12T18:00:00Z', max: 7500, unit: 'tokens' },
            { id: 'op_may_early', nameKey: 'act_op_may_early', utcStart: '2026-05-01T18:00:00Z', utcEnd: '2026-06-01T18:00:00Z', max: 3000, unit: 'tokens' },
            { id: 'op_may_late', nameKey: 'act_op_may_late', utcStart: '2026-05-22T18:00:00Z', utcEnd: '2026-06-02T18:00:00Z', max: 3000, unit: 'tokens' },
            { id: 'op_solstice', nameKey: 'act_op_solstice', utcStart: '2026-06-05T18:00:00Z', utcEnd: '2026-06-22T18:00:00Z', max: 3000, unit: 'tokens' },
            { id: 'anomaly', nameKey: 'act_anomaly', descKey: 'desc_anomaly', max: 30000, unit: 'tokens' }
        ],
        i18n: {
            zh: {
                pageTitle: 'ORION 赛季计划工具',
                pageSubtitle: '2026 Q2 (4/8 - 6/30)',
                cardTitle: 'INGRESS ORION 赛季',
                footerSource: '来源：Ingress 2026 Q2 Orion 赛季说明。所有输入数据均在本地浏览器存储。',
                act_bounties: '每日任务 (Daily Bounties)',
                act_ifs_apr: 'IFS - 四月',
                act_ifs_may: 'IFS - 五月',
                act_ifs_jun: 'IFS - 六月',
                act_op_sakura: 'Dispatch: 樱花祭',
                act_op_global: 'Orion 全球行动',
                act_op_may_early: 'Nemesis Redux: Myriad',
                act_op_may_late: 'Hank Johnson: The Courier Files',
                act_op_solstice: 'Dispatch: 夏至',
                act_anomaly: 'Anomaly 现场行动',
                desc_bounties: '4/8 - 6/30 (84天), 每天满额 80 tokens',
                desc_ifs_apr: '4/4 现场活动',
                desc_ifs_may: '5/2 现场活动',
                desc_ifs_jun: '6/6 现场活动',
                desc_anomaly: '单站最高 5000 tokens',
                max_anomaly: '5000 x 场次',
            },
            en: {
                pageTitle: 'ORION SEASON PLANNER',
                pageSubtitle: '2026 Q2 (Apr 8 - Jun 30)',
                cardTitle: 'INGRESS ORION SEASON',
                footerSource: 'Source: Ingress 2026 Q2 Orion Season. All data is stored locally in this browser.',
                act_bounties: 'Daily Bounties',
                act_ifs_apr: 'IFS - April',
                act_ifs_may: 'IFS - May',
                act_ifs_jun: 'IFS - June',
                act_op_sakura: 'Dispatch: Sakura Festival',
                act_op_global: 'Orion Global Operation',
                act_op_may_early: 'Nemesis Redux: Myriad',
                act_op_may_late: 'Hank Johnson: The Courier Files',
                act_op_solstice: 'Dispatch: Summer Solstice',
                act_anomaly: 'Anomaly On-site',
                desc_bounties: 'Apr 8 - Jun 30 (84 days), up to 80 tokens/day',
                desc_ifs_apr: 'Apr 4 on-site event',
                desc_ifs_may: 'May 2 on-site event',
                desc_ifs_jun: 'Jun 6 on-site event',
                desc_anomaly: 'Up to 5000 tokens per site',
                max_anomaly: '5000 x #sites',
            },
            ja: {
                pageTitle: 'ORION シーズンプランナー',
                pageSubtitle: '2026 Q2 (4/8 - 6/30)',
                cardTitle: 'INGRESS ORION シーズン',
                footerSource: '出典：Ingress 2026 Q2 Orion シーズン説明。すべてのデータはブラウザにローカル保存されます。',
                act_bounties: 'デイリーバウンティ',
                act_ifs_apr: 'IFS - 4月',
                act_ifs_may: 'IFS - 5月',
                act_ifs_jun: 'IFS - 6月',
                act_op_sakura: 'Dispatch: 桜まつり',
                act_op_global: 'Orion グローバルオペレーション',
                act_op_may_early: 'Nemesis Redux: Myriad',
                act_op_may_late: 'Hank Johnson: The Courier Files',
                act_op_solstice: 'Dispatch: 夏至',
                act_anomaly: 'XMアノマリー',
                desc_bounties: '4/8 - 6/30 (84日間), 1日最大 80 tokens',
                desc_ifs_apr: '4/4 現地イベント',
                desc_ifs_may: '5/2 現地イベント',
                desc_ifs_jun: '6/6 現地イベント',
                desc_anomaly: '1サイト最大 5000 tokens',
                max_anomaly: '5000 x サイト数',
            },
            de: {
                pageTitle: 'ORION SAISONPLANER',
                pageSubtitle: '2026 Q2 (8. Apr. - 30. Juni)',
                cardTitle: 'INGRESS ORION SAISON',
                footerSource: 'Quelle: Ingress 2026 Q2 Orion Saison. Alle Daten werden lokal in diesem Browser gespeichert.',
                act_bounties: 'Tägliche Bounties',
                act_ifs_apr: 'IFS - April',
                act_ifs_may: 'IFS - Mai',
                act_ifs_jun: 'IFS - Juni',
                act_op_sakura: 'Dispatch: Kirschblütenfest',
                act_op_global: 'Orion Globale Operation',
                act_op_may_early: 'Nemesis Redux: Myriad',
                act_op_may_late: 'Hank Johnson: The Courier Files',
                act_op_solstice: 'Dispatch: Sommersonnenwende',
                act_anomaly: 'XM-Anomalie Vor Ort',
                desc_bounties: '8. Apr. - 30. Juni (84 Tage), bis zu 80 Token/Tag',
                desc_ifs_apr: '4. Apr. Vor-Ort-Event',
                desc_ifs_may: '2. Mai Vor-Ort-Event',
                desc_ifs_jun: '6. Juni Vor-Ort-Event',
                desc_anomaly: 'Bis zu 5000 Token pro Standort',
                max_anomaly: '5000 x Anzahl Standorte',
            }
        }
    },
    "2026_q3_apollo": {
        id: "2026_q3_apollo",
        name: "Apollo Anomaly Season (2026 Q3)",
        cardEnabled: false,
        badgePath: "static/apollo/",
        endTime: "2026-09-30T23:59:59",
        tiers: [
            { name: 'Bronze', value: 4000, color: 'rgba(205,127,50,0.5)' },
            { name: 'Silver', value: 8000, color: 'rgba(192,192,192,0.5)' },
            { name: 'Gold', value: 16000, color: 'rgba(255,215,0,0.5)' }
        ],
        activities: [
            { id: 'bounties', nameKey: 'act_bounties', descKey: 'desc_bounties', localStart: '2026-07-01T00:00:00', localEnd: '2026-09-18T23:59:59', max: 4800, dailyMax: 60, unit: 'tokens', isBounty: true },
            { id: 'ifs_jul', nameKey: 'act_ifs_jul', descKey: 'desc_ifs_jul', type: 'binary', max: 2500, unit: 'tokens' },
            { id: 'ifs_aug', nameKey: 'act_ifs_aug', descKey: 'desc_ifs_aug', type: 'binary', max: 2500, unit: 'tokens' },
            { id: 'ifs_sep', nameKey: 'act_ifs_sep', descKey: 'desc_ifs_sep', type: 'binary', max: 2500, unit: 'tokens' },
            { id: 'op_july_dispatch', nameKey: 'act_op_july_dispatch', utcStart: '2026-07-01T18:00:00Z', utcEnd: '2026-07-31T18:00:00Z', presets: [0, 1000, 2500], max: 2500, unit: 'tokens' },
            { id: 'op_july_dispatch_2', nameKey: 'act_op_july_dispatch_2', utcStart: '2026-07-15T18:00:00Z', utcEnd: '2026-08-14T18:00:00Z', presets: [0, 1000, 2500], max: 2500, unit: 'tokens' },
            { id: 'op_august_dispatch', nameKey: 'act_op_august_dispatch', type: 'presets', utcStart: '2026-07-31T18:00:00Z', utcEnd: '2026-08-31T18:00:00Z', max: 2500, unit: 'tokens' },
            { id: 'op_autumn_equinox', nameKey: 'act_op_autumn_equinox', type: 'presets', utcStart: '2026-09-01T18:00:00Z', utcEnd: '2026-09-30T18:00:00Z', max: 2500, unit: 'tokens' },
            { id: 'op_global_apollo', nameKey: 'act_op_global_apollo', descKey: 'desc_op_global_apollo', type: 'presets', utcStart: '2026-08-26T18:00:00Z', utcEnd: '2026-09-16T18:00:00Z', max: 10000, unit: 'tokens' },
            { id: 'anomaly', nameKey: 'act_anomaly', descKey: 'desc_anomaly', type: 'incremental', presets: [3000, 5000], max: 30000, unit: 'tokens' }
        ],
        i18n: {
            zh: {
                pageTitle: 'APOLLO 赛季计划工具',
                pageSubtitle: '2026 Q3 (7/1 - 9/30)',
                cardTitle: 'INGRESS APOLLO 赛季',
                footerSource: '来源：Ingress 2026 Q3 Apollo 赛季说明。所有输入数据均在本地浏览器存储。',
                act_bounties: '每日任务 (Daily Bounties)',
                act_ifs_jul: 'IFS - 七月',
                act_ifs_aug: 'IFS - 八月',
                act_ifs_sep: 'IFS - 九月',
                act_op_july_dispatch: 'Red Codex 行动',
                act_op_july_dispatch_2: 'Moonlit Paths 行动',
                act_op_august_dispatch: 'Dispatch: ▓▓▓▓▓▓▓ (八月)',
                act_op_autumn_equinox: 'Dispatch: 2026 秋分',
                act_op_global_apollo: 'Apollo 全球行动',
                act_anomaly: 'Anomaly 现场行动',
                desc_bounties: '7/1 - 9/18 (80天), 每天满额 60 tokens',
                desc_ifs_jul: '7/4 现场活动。每位参与者最高可为阵营赢得 0.1 赛季分。',
                desc_ifs_aug: '8/1 现场活动。每位参与者最高可为阵营赢得 0.1 赛季分。',
                desc_ifs_sep: '9/5 现场活动。每位参与者最高可为阵营赢得 0.1 赛季分。',
                desc_op_august_dispatch: '详情将于8月初公布',
                desc_op_autumn_equinox: 'Dispatch 行动活动',
                desc_op_global_apollo: '根据实际完成的任务争夺 2,000 赛季分。',
                desc_anomaly: '每站争夺 300 赛季分。',
                max_anomaly: '5000 x 场次',
            },
            en: {
                pageTitle: 'APOLLO SEASON PLANNER',
                pageSubtitle: '2026 Q3 (Jul 1 - Sep 30)',
                cardTitle: 'INGRESS APOLLO SEASON',
                footerSource: 'Source: Ingress 2026 Q3 Apollo Season. All data is stored locally in this browser.',
                act_bounties: 'Daily Bounties',
                act_ifs_jul: 'IFS - July',
                act_ifs_aug: 'IFS - August',
                act_ifs_sep: 'IFS - September',
                act_op_july_dispatch: 'Operation Red Codex',
                act_op_july_dispatch_2: 'Operation Moonlit Paths',
                act_op_august_dispatch: 'Dispatch: ▓▓▓▓▓▓▓ (August)',
                act_op_autumn_equinox: 'Dispatch: Autumn Equinox 2026',
                act_op_global_apollo: 'Apollo Global Campaign',
                act_anomaly: 'Anomaly On-site',
                desc_bounties: 'Jul 1 - Sep 18 (80 days), up to 60 tokens/day',
                desc_ifs_jul: 'Jul 4 on-site event. Up to 0.1 Season Points for your faction per participant.',
                desc_ifs_aug: 'Aug 1 on-site event. Up to 0.1 Season Points for your faction per participant.',
                desc_ifs_sep: 'Sep 5 on-site event. Up to 0.1 Season Points for your faction per participant.',
                desc_op_august_dispatch: 'Details to be released by early August',
                desc_op_autumn_equinox: 'Dispatch operation event',
                desc_op_global_apollo: '2,000 Season Points distributed based on completed assignments.',
                desc_anomaly: '300 Season Points distributed per site.',
                max_anomaly: '5000 x #sites',
            },
            ja: {
                pageTitle: 'APOLLO シーズンプランナー',
                pageSubtitle: '2026 Q3 (7/1 - 9/30)',
                cardTitle: 'INGRESS APOLLO シーズン',
                footerSource: '出典：Ingress 2026 Q3 Apollo シーズン説明。すべてのデータはブラウザにローカル保存されます。',
                act_bounties: 'デイリーバウンティ',
                act_ifs_jul: 'IFS - 7月',
                act_ifs_aug: 'IFS - 8月',
                act_ifs_sep: 'IFS - 9月',
                act_op_july_dispatch: '作戦 Red Codex',
                act_op_july_dispatch_2: '作戦 Moonlit Paths',
                act_op_august_dispatch: 'Dispatch: ▓▓▓▓▓▓▓ (8月)',
                act_op_autumn_equinox: 'Dispatch: 秋分 2026',
                act_op_global_apollo: 'Apollo グローバルキャンペーン',
                act_anomaly: 'XMアノマリー',
                desc_bounties: '7/1 - 9/18 (80日間), 1日最大 60 tokens',
                desc_ifs_jul: '7/4 現地イベント。参加者1人につき最大0.1シーズンポイントが陣営に加算されます。',
                desc_ifs_aug: '8/1 現地イベント。参加者1人につき最大0.1シーズンポイントが陣営に加算されます。',
                desc_ifs_sep: '9/5 現地イベント。参加者1人につき最大0.1シーズンポイントが陣営に加算されます。',
                desc_op_august_dispatch: '詳細は8月初旬に公開予定',
                desc_op_autumn_equinox: 'Dispatch 作戦イベント',
                desc_op_global_apollo: 'タスク完了実績に基づき、両陣営に計2,000シーズンポイントを争奪。',
                desc_anomaly: '1サイトあたり両陣営に計300シーズンポイントを争奪。',
                max_anomaly: '5000 x サイト数',
            },
            de: {
                pageTitle: 'APOLLO SAISONPLANER',
                pageSubtitle: '2026 Q3 (1. Jul. - 30. Sep.)',
                cardTitle: 'INGRESS APOLLO SAISON',
                footerSource: 'Quelle: Ingress 2026 Q3 Apollo Saison. Alle Daten werden lokal in diesem Browser gespeichert.',
                act_bounties: 'Tägliche Bounties',
                act_ifs_jul: 'IFS - Juli',
                act_ifs_aug: 'IFS - August',
                act_ifs_sep: 'IFS - September',
                act_op_july_dispatch: 'Operation Red Codex',
                act_op_july_dispatch_2: 'Operation Moonlit Paths',
                act_op_august_dispatch: 'Dispatch: ▓▓▓▓▓▓▓ (August)',
                act_op_autumn_equinox: 'Dispatch: Herbst-Tagundnachtgleiche 2026',
                act_op_global_apollo: 'Apollo Globale Kampagne',
                act_anomaly: 'XM-Anomalie Vor Ort',
                desc_bounties: '1. Jul. - 18. Sep. (80 Tage), bis zu 60 Token/Tag',
                desc_ifs_jul: '4. Jul. Vor-Ort-Event. Bis zu 0,1 Saisonpunkte für deine Fraktion pro Teilnehmer.',
                desc_ifs_aug: '1. Aug. Vor-Ort-Event. Bis zu 0,1 Saisonpunkte für deine Fraktion pro Teilnehmer.',
                desc_ifs_sep: '5. Sep. Vor-Ort-Event. Bis zu 0,1 Saisonpunkte für deine Fraktion pro Teilnehmer.',
                desc_op_august_dispatch: 'Details werden Anfang August veröffentlicht',
                desc_op_autumn_equinox: 'Dispatch-Operation-Event',
                desc_op_global_apollo: '2.000 Saisonpunkte werden basierend auf den abgeschlossenen Aufgaben verteilt.',
                desc_anomaly: '300 Saisonpunkte werden pro Standort verteilt.',
                max_anomaly: '5000 x Anzahl Standorte',
            }
        }
    }
};
